(define (problem problemgotocity)
(:domain domaingotocity)
(:objects city_g city_i city_h city_q city_y city_m city_z city_p city_a city_k city_c city_e city_j city_x city_d - city)
(:init 
(has_taxi city_g city_k)
(has_taxi city_x city_d)
(neighboring city_k city_c)
(has_taxi city_j city_x)
(has_taxi city_e city_j)
(has_bus city_c city_e)
(has_taxi city_y city_z)
(neighboring city_c city_e)
(neighboring city_g city_k)
(neighboring city_g city_i)
(neighboring city_x city_d)
(neighboring city_h city_q)
(neighboring city_e city_j)
(neighboring city_z city_p)
(at city_g)
(has_taxi city_q city_y)
(has_bus city_x city_c)
(has_bus city_g city_i)
(has_taxi city_y city_m)
(has_bus city_m city_z)
(has_taxi city_k city_c)
(neighboring city_i city_h)
(neighboring city_g city_a)
(has_bus city_g city_a)
(neighboring city_m city_z)
(neighboring city_y city_m)
(has_taxi city_i city_h)
(neighboring city_q city_y)
(neighboring city_j city_x)
)
(:goal 
    (and
(at city_p)
)
)
)
